### ISSUE TITLE
Fix reddeer dependency range for org.jboss.ide.eclipse.as.ui.bot.test

### ISSUE THREAD

**Issue by vpakan** [jbosstools/jbosstools-integration-tests#1430]
@mmalina org.jboss.reddeer.go dependency range should be 1.0.0 and above

**Comment by mmalina** [comment]
It's there:
https://github.com/jbosstools/jbosstools-integration-tests/blob/master/tests/org.jboss.ide.eclipse.as.ui.bot.test/META-INF/MANIFEST.MF#L13

**Comment by mmalina** [comment]
(Fixed by @jrichter1 in #1431 )
